
services:

  # ========== Data Bus ==========
  kafka:
    image: apache/kafka:3.9.0
    container_name: streammart-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: streammart-kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: streammart
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8082:8080"
    depends_on:
      - kafka

  # ========== Storage ==========
  minio:
    image: quay.io/vakamo/minio-cicd:2025-12-01
    hostname: minio
    container_name: streammart-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: streammart/raw,meta/checkpoints
    ports:
      - "9000:9000"
      - "9001:9001"

  postgres:
    image: postgres:16.2-alpine
    container_name: streammart-postgres
    environment:
      POSTGRES_USER: streammart
      POSTGRES_PASSWORD: streammart
      POSTGRES_DB: streammart
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"


  # ========== Compute ==========
  spark-master:
    image: apache/spark-py:v3.4.0
    container_name: streammart-spark-master
    hostname: spark-master
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_LOG_DIR: /tmp/spark-logs
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./spark/jobs:/opt/spark/jobs
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: apache/spark-py:v3.4.0
    container_name: streammart-spark-worker
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_DIR: /tmp/spark-work
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark/jobs:/opt/spark/jobs
    depends_on:
      - spark-master

  # ========== Orchestration ==========
  airflow-webserver:
    image: apache/airflow:2.10.2-python3.11
    container_name: streammart-airflow
    command: webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://streammart:streammart@postgres:5432/airflow
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  airflow-scheduler:
    image: apache/airflow:2.10.2-python3.11
    container_name: streammart-airflow-scheduler
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://streammart:streammart@postgres:5432/airflow
    depends_on:
      - airflow-webserver

  # ========== Monitoring ==========
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: streammart-prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.3.0
    container_name: streammart-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"